on:
  push:
    branches:
      - 'main'
name: Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Upload file via SSH
        uses: appleboy/scp-action@master
        with:
          host: apps.creatusdev.com
          username: root
          password: ${{secrets.PASSWORD}}
          source: './*'
          target: '/root/apps/minicurso/tmp/minicurso-back'
      - name: Remote commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: apps.creatusdev.com
          username: root
          password: ${{secrets.PASSWORD}}
          port: 22
          script: |
            cd /root/apps/minicurso/minicurso-back
            docker compose down
            docker system prune -a -f
            cd ..
            rm -rf /root/apps/minicurso/minicurso-back
            mv /root/apps/minicurso/tmp/minicurso-back /root/apps/minicurso/minicurso-back
            cd minicurso-back
            docker compose up -d --build
            docker system prune -a -f
